### ISSUE TITLE
deprecate this style in favor of Coloured Streets

### ISSUE THREAD

**Issue by Klumbumbus** [simon04/coloured-addresses.mapcss#2]
I suggest to deprecate or remove this style in favor of https://josm.openstreetmap.de/wiki/Styles/Coloured_Streets, which is much more advanced and up to date.

Similyr was done for Address Tags Validator: https://josm.openstreetmap.de/wiki/Styles/AddressValidator?action=diff&version=17

**Comment by simon04** [comment]
Readme /w deprecation notice added in 2ad68712ed55c9a43aff8fc8de0cd146111e2fc8, removed from https://josm.openstreetmap.de/wiki/StylesSource via https://josm.openstreetmap.de/wiki/StylesSource?action=diff&version=30&old_version=29
